import {
	AdocIcon,
	AfdesignIcon,
	AfphotoIcon,
	AfpubIcon,
	AiIcon,
	AnimIcon,
	AstroIcon,
	Audiomp3Icon,
	AudiooggIcon,
	AudiowavIcon,
	AudiowvIcon,
	BallerinaIcon,
	BatIcon,
	BazelIcon,
	BazelignoreIcon,
	BicepIcon,
	BicepparamIcon,
	BinaryIcon,
	BladeIcon,
	BrotliIcon,
	BrunoIcon,
	BundlerIcon,
	CIcon,
	CertIcon,
	CheaderIcon,
	CivetIcon,
	CliIcon,
	ClojureIcon,
	ConfIcon,
	CppIcon,
	CrystalIcon,
	CsharpIcon,
	CshtmlIcon,
	CsprojIcon,
	CssIcon,
	CssmapIcon,
	CsvIcon,
	CucumberIcon,
	CursorIcon,
	CypressjsIcon,
	CypresstsIcon,
	DIcon,
	DartlangIcon,
	DelphiprojectIcon,
	DiffIcon,
	DockerIcon,
	DrawioIcon,
	EdgeIcon,
	EexIcon,
	ElixirIcon,
	ElmIcon,
	EnvIcon,
	EraserIcon,
	ErbIcon,
	ErlangIcon,
	ExcalidrawIcon,
	ExsIcon,
	FigmaIcon,
	FileIcon,
	FreemarkerIcon,
	FsharpIcon,
	GblIcon,
	GleamIcon,
	GoIcon,
	GodotIcon,
	GradleIcon,
	GradlekotlinIcon,
	GrainIcon,
	GraphqlIcon,
	GroovyIcon,
	HamlIcon,
	HandlebarsIcon,
	HashIcon,
	HashicorpIcon,
	HaskellIcon,
	HaxeIcon,
	HaxemlIcon,
	HppIcon,
	HtmlIcon,
	HttpIcon,
	IdentifierIcon,
	ImagegifIcon,
	ImageicoIcon,
	ImagejpgIcon,
	ImagepngIcon,
	ImagewebpIcon,
	ImbaIcon,
	InfoIcon,
	InstructionsIcon,
	IpynbIcon,
	JarIcon,
	JavaIcon,
	JestIcon,
	JinjaIcon,
	JsIcon,
	JsmapIcon,
	JsonIcon,
	JspIcon,
	JuliaIcon,
	KeyIcon,
	KotlinIcon,
	KotlinsIcon,
	KritaIcon,
	LatexIcon,
	LazarusprojectIcon,
	LessIcon,
	LicenseIcon,
	LiquidIcon,
	LlvmIcon,
	LockIcon,
	LogIcon,
	MIcon,
	MakefileIcon,
	ManifestIcon,
	MarkdownIcon,
	MarkdownxIcon,
	MermaidIcon,
	MeshIcon,
	MgcbIcon,
	MintIcon,
	MjmlIcon,
	MotokoIcon,
	MovIcon,
	Mp4Icon,
	MtlIcon,
	MustacheIcon,
	NeluaIcon,
	NeonIcon,
	NestjscontrollerIcon,
	NestjsdecoratorIcon,
	NestjsdtoIcon,
	NestjsentityIcon,
	NestjsfilterIcon,
	NestjsguardIcon,
	NestjsinterceptorIcon,
	NestjsmoduleIcon,
	NestjsrepositoryIcon,
	NestjsresolverIcon,
	NestjsserviceIcon,
	NestschedulerIcon,
	NimIcon,
	NixIcon,
	NjkIcon,
	ObjIcon,
	OcamlIcon,
	OcamliIcon,
	OcamllIcon,
	OcamlyIcon,
	OdinIcon,
	OpenglIcon,
	PascalIcon,
	PdfIcon,
	PerlIcon,
	PerlmIcon,
	PfxIcon,
	PhotoshopIcon,
	PhpIcon,
	PlantumlIcon,
	PostcssconfigIcon,
	PowershellIcon,
	PowershelldataIcon,
	PowershellmoduleIcon,
	PrismaIcon,
	PrologIcon,
	PropertiesIcon,
	ProtoIcon,
	PvkIcon,
	QtIcon,
	RacketIcon,
	RazorIcon,
	ReactjsIcon,
	ReacttsIcon,
	RegoIcon,
	RescriptIcon,
	RescriptinterfaceIcon,
	RjsonIcon,
	RonIcon,
	RubyIcon,
	RustIcon,
	SalesforceIcon,
	ScalaIcon,
	ScssIcon,
	SentinelIcon,
	ShaderlabIcon,
	ShellIcon,
	SilqIcon,
	SlimIcon,
	SlnIcon,
	SmartyIcon,
	SolIcon,
	SpcIcon,
	SqlIcon,
	SqliteIcon,
	StorybookIcon,
	StylusIcon,
	SuoIcon,
	SvelteIcon,
	SvgIcon,
	SwiftIcon,
	TerraformIcon,
	TerraformvarsIcon,
	TestjsIcon,
	TesttsIcon,
	TmplIcon,
	TodoIcon,
	TomlIcon,
	TresIcon,
	TscnIcon,
	TwigIcon,
	TxtIcon,
	TypescriptdefIcon,
	UiIcon,
	UserIcon,
	VIcon,
	VanillaextractIcon,
	VhdIcon,
	VhdlIcon,
	VscodeIcon,
	WasmIcon,
	WgslIcon,
	WrenIcon,
	XmlIcon,
	YangIcon,
	YinIcon,
	ZigIcon,
	ZipIcon,
} from './icons';

export default {
	'7z': ZipIcon,
	'7zip': ZipIcon,
	'blade.php': BladeIcon,
	'cfg.dist': ConfIcon,
	'cjs.map': JsmapIcon,
	'controller.js': NestjscontrollerIcon,
	'controller.ts': NestjscontrollerIcon,
	'repository.js': NestjsrepositoryIcon,
	'repository.ts': NestjsrepositoryIcon,
	'scheduler.js': NestschedulerIcon,
	'scheduler.ts': NestschedulerIcon,
	'css.js': VanillaextractIcon,
	'css.ts': VanillaextractIcon,
	'css.map': CssmapIcon,
	'd.ts': TypescriptdefIcon,
	'decorator.js': NestjsdecoratorIcon,
	'decorator.ts': NestjsdecoratorIcon,
	'drawio.png': DrawioIcon,
	'drawio.svg': DrawioIcon,
	'e2e-spec.ts': TesttsIcon,
	'e2e-spec.tsx': TesttsIcon,
	'e2e-test.ts': TesttsIcon,
	'e2e-test.tsx': TesttsIcon,
	'filter.js': NestjsfilterIcon,
	'filter.ts': NestjsfilterIcon,
	'format.ps1xml': PowershellIcon,
	'gemfile.lock': BundlerIcon,
	'gradle.kts': GradlekotlinIcon,
	'guard.js': NestjsguardIcon,
	'guard.ts': NestjsguardIcon,
	'jar.old': JarIcon,
	'js.flow': JsIcon,
	'js.map': JsmapIcon,
	'js.snap': JestIcon,
	'json-ld': JsonIcon,
	'jsx.snap': JestIcon,
	'layout.htm': HtmlIcon,
	'layout.html': HtmlIcon,
	'marko.js': JsIcon,
	'mjs.map': JsmapIcon,
	'module.ts': NestjsmoduleIcon,
	'resolver.js': NestjsresolverIcon,
	'resolver.ts': NestjsresolverIcon,
	'service.js': NestjsserviceIcon,
	'service.ts': NestjsserviceIcon,
	'entity.js': NestjsentityIcon,
	'entity.ts': NestjsentityIcon,
	'interceptor.js': NestjsinterceptorIcon,
	'interceptor.ts': NestjsinterceptorIcon,
	'dto.js': NestjsdtoIcon,
	'dto.ts': NestjsdtoIcon,
	'spec.js': TestjsIcon,
	'spec.jsx': TestjsIcon,
	'spec.mjs': TestjsIcon,
	'spec.ts': TesttsIcon,
	'spec.tsx': TesttsIcon,
	'stories.js': StorybookIcon,
	'stories.jsx': StorybookIcon,
	'stories.ts': StorybookIcon,
	'stories.tsx': StorybookIcon,
	'stories.svelte': StorybookIcon,
	'story.js': StorybookIcon,
	'story.jsx': StorybookIcon,
	'story.ts': StorybookIcon,
	'story.tsx': StorybookIcon,
	'story.svelte': StorybookIcon,
	'test.cjs': TestjsIcon,
	'test.cts': TesttsIcon,
	'test.js': TestjsIcon,
	'test.jsx': TestjsIcon,
	'test.mjs': TestjsIcon,
	'test.mts': TesttsIcon,
	'test.ts': TesttsIcon,
	'test.tsx': TesttsIcon,
	'ts.snap': JestIcon,
	'tsx.snap': JestIcon,
	'types.ps1xml': PowershellIcon,
	a: BinaryIcon,
	accda: FileIcon,
	accdb: FileIcon,
	accdc: FileIcon,
	accde: FileIcon,
	accdp: FileIcon,
	accdr: FileIcon,
	accdt: FileIcon,
	accdu: FileIcon,
	ade: FileIcon,
	adoc: AdocIcon,
	adp: FileIcon,
	afdesign: AfdesignIcon,
	affinitydesigner: AfdesignIcon,
	affinityphoto: AfphotoIcon,
	affinitypublisher: AfpubIcon,
	afphoto: AfphotoIcon,
	afpub: AfpubIcon,
	ai: AiIcon,
	app: BinaryIcon,
	ascx: HtmlIcon,
	asm: BinaryIcon,
	aspx: HtmlIcon,
	astro: AstroIcon,
	awk: ShellIcon,
	bat: BatIcon,
	bc: LlvmIcon,
	bcmx: FileIcon,
	bicep: BicepIcon,
	bin: BinaryIcon,
	blade: BladeIcon,
	bz2: ZipIcon,
	bzip2: ZipIcon,
	c: CIcon,
	cake: FileIcon,
	cer: CertIcon,
	pvk: PvkIcon,
	pfx: PfxIcon,
	spc: SpcIcon,
	cfg: ConfIcon,
	civet: CivetIcon,
	cjm: ClojureIcon,
	cl: OpenglIcon,
	class: FileIcon,
	cli: CliIcon,
	clj: ClojureIcon,
	cljc: ClojureIcon,
	cljs: ClojureIcon,
	cljx: ClojureIcon,
	cma: BinaryIcon,
	cmd: CliIcon,
	cmi: BinaryIcon,
	cmo: BinaryIcon,
	cmx: BinaryIcon,
	cmxa: BinaryIcon,
	comp: OpenglIcon,
	conf: ConfIcon,
	cpp: CppIcon,
	cr: CrystalIcon,
	crec: FileIcon,
	crl: CertIcon,
	crt: CertIcon,
	cs: CsharpIcon,
	cshtml: CshtmlIcon,
	csproj: CsprojIcon,
	csr: CertIcon,
	css: CssIcon,
	csv: CsvIcon,
	csx: CsharpIcon,
	d: DIcon,
	dart: DartlangIcon,
	db: SqliteIcon,
	db3: SqliteIcon,
	der: CertIcon,
	diff: DiffIcon,
	dio: DrawioIcon,
	djt: FileIcon,
	dll: BinaryIcon,
	dmp: LogIcon,
	doc: FileIcon,
	docm: FileIcon,
	docx: FileIcon,
	dot: FileIcon,
	dotm: FileIcon,
	dotx: FileIcon,
	drawio: DrawioIcon,
	dta: FileIcon,
	eco: FileIcon,
	edge: EdgeIcon,
	edn: ClojureIcon,
	eex: EexIcon,
	ejs: HtmlIcon,
	el: FileIcon,
	elc: FileIcon,
	elm: ElmIcon,
	enc: LicenseIcon,
	ensime: FileIcon,
	env: EnvIcon,
	eps: FileIcon,
	erb: ErbIcon,
	erl: ErlangIcon,
	eskip: FileIcon,
	ex: ElixirIcon,
	exe: BinaryIcon,
	exp: FileIcon,
	exs: ExsIcon,
	fbx: FileIcon,
	feature: CucumberIcon,
	fig: FigmaIcon,
	fish: ShellIcon,
	fla: FileIcon,
	fods: FileIcon,
	frag: OpenglIcon,
	fs: FsharpIcon,
	fsproj: CsprojIcon,
	ftl: FreemarkerIcon,
	gbl: GblIcon,
	gd: GodotIcon,
	gemfile: BundlerIcon,
	geom: OpenglIcon,
	gif: ImagegifIcon,
	glsl: OpenglIcon,
	gmx: FileIcon,
	go: GoIcon,
	godot: GodotIcon,
	gql: GraphqlIcon,
	gradle: GradleIcon,
	groovy: GroovyIcon,
	gz: ZipIcon,
	h: CheaderIcon,
	haml: HamlIcon,
	hbs: HandlebarsIcon,
	hcl: HashicorpIcon,
	hl: BinaryIcon,
	hlsl: OpenglIcon,
	hpp: HppIcon,
	hs: HaskellIcon,
	html: HtmlIcon,
	hxp: FileIcon,
	hxproj: FileIcon,
	ibc: FileIcon,
	ico: ImageicoIcon,
	idr: FileIcon,
	ilk: BinaryIcon,
	imba: ImbaIcon,
	inc: FileIcon,
	include: FileIcon,
	info: InfoIcon,
	infopathxml: FileIcon,
	ini: ConfIcon,
	ino: FileIcon,
	ipkg: FileIcon,
	ipynb: IpynbIcon,
	iuml: PlantumlIcon,
	jar: JarIcon,
	java: JavaIcon,
	jbuilder: FileIcon,
	jpeg: ImagejpgIcon,
	j2: JinjaIcon,
	jinja: JinjaIcon,
	jinja2: JinjaIcon,
	jl: JuliaIcon,
	jpg: ImagejpgIcon,
	json5: JsonIcon,
	jsonld: JsonIcon,
	jsp: JspIcon,
	jss: JsIcon,
	key: KeyIcon,
	kit: FileIcon,
	kt: KotlinIcon,
	kts: KotlinsIcon,
	laccdb: FileIcon,
	ldb: FileIcon,
	less: LessIcon,
	lib: BinaryIcon,
	lidr: FileIcon,
	liquid: LiquidIcon,
	ll: LlvmIcon,
	lnk: FileIcon,
	log: LogIcon,
	ls: FileIcon,
	lucee: FileIcon,
	m: MIcon,
	makefile: MakefileIcon,
	mam: FileIcon,
	map: FileIcon,
	maq: FileIcon,
	markdown: MarkdownIcon,
	master: HtmlIcon,
	mdb: FileIcon,
	mdown: MarkdownIcon,
	mdw: FileIcon,
	mdx: MarkdownxIcon,
	mesh: MeshIcon,
	mex: FileIcon,
	mexn: FileIcon,
	mexrs6: FileIcon,
	mf: ManifestIcon,
	mint: MintIcon,
	mjml: MjmlIcon,
	ml: OcamlIcon,
	mli: OcamliIcon,
	mll: OcamllIcon,
	mly: OcamlyIcon,
	mn: FileIcon,
	mo: MotokoIcon,
	mov: MovIcon,
	mp3: Audiomp3Icon,
	mp4: Mp4Icon,
	msg: FileIcon,
	mst: MustacheIcon,
	mum: FileIcon,
	mustache: MustacheIcon,
	mx: FileIcon,
	mx3: FileIcon,
	n: BinaryIcon,
	ndll: BinaryIcon,
	neon: NeonIcon,
	nim: NimIcon,
	nix: NixIcon,
	njk: NjkIcon,
	njs: FileIcon,
	njsproj: CsprojIcon,
	nunj: FileIcon,
	nupkg: FileIcon,
	nuspec: FileIcon,
	nvim: FileIcon,
	o: BinaryIcon,
	ocrec: FileIcon,
	ods: FileIcon,
	oft: FileIcon,
	ogg: AudiooggIcon,
	one: FileIcon,
	onepkg: FileIcon,
	onetoc: FileIcon,
	onetoc2: FileIcon,
	opencl: OpenglIcon,
	org: FileIcon,
	otf: FileIcon,
	otm: FileIcon,
	ovpn: FileIcon,
	P: PrologIcon,
	p12: CertIcon,
	p7b: CertIcon,
	p7r: CertIcon,
	pa: FileIcon,
	patch: DiffIcon,
	pcd: FileIcon,
	pck: FileIcon,
	pdb: BinaryIcon,
	pde: FileIcon,
	pdf: PdfIcon,
	pem: KeyIcon,
	pex: XmlIcon,
	phar: PhpIcon,
	php1: PhpIcon,
	php2: PhpIcon,
	php3: PhpIcon,
	php4: PhpIcon,
	php5: PhpIcon,
	php6: PhpIcon,
	phps: PhpIcon,
	phpsa: PhpIcon,
	phpt: PhpIcon,
	phtml: PhpIcon,
	pkb: FileIcon,
	pkg: FileIcon,
	pkh: FileIcon,
	pks: FileIcon,
	pl: PerlIcon,
	plantuml: PlantumlIcon,
	plist: ConfIcon,
	pm: PerlmIcon,
	png: ImagepngIcon,
	po: FileIcon,
	postcss: PostcssconfigIcon,
	pcss: PostcssconfigIcon,
	pot: FileIcon,
	potm: FileIcon,
	potx: FileIcon,
	ppa: FileIcon,
	ppam: FileIcon,
	pps: FileIcon,
	ppsm: FileIcon,
	ppsx: FileIcon,
	ppt: FileIcon,
	pptm: FileIcon,
	pptx: FileIcon,
	pri: QtIcon,
	prisma: PrismaIcon,
	pro: PrologIcon,
	properties: PropertiesIcon,
	ps1: PowershellIcon,
	psd: PhotoshopIcon,
	psd1: PowershelldataIcon,
	psm1: PowershellmoduleIcon,
	psmdcp: FileIcon,
	pst: FileIcon,
	pu: PlantumlIcon,
	pub: FileIcon,
	puml: PlantumlIcon,
	puz: FileIcon,
	pyc: BinaryIcon,
	pyd: BinaryIcon,
	pyo: BinaryIcon,
	q: FileIcon,
	qbs: FileIcon,
	qvd: FileIcon,
	qvw: FileIcon,
	rake: RacketIcon,
	rar: ZipIcon,
	gzip: ZipIcon,
	razor: RazorIcon,
	rb: RubyIcon,
	reg: FileIcon,
	rego: RegoIcon,
	res: RescriptIcon,
	resi: RescriptinterfaceIcon,
	rjson: RjsonIcon,
	rproj: FileIcon,
	rs: RustIcon,
	rsx: RustIcon,
	ron: RonIcon,
	odin: OdinIcon,
	rt: FileIcon,
	rwd: FileIcon,
	pas: PascalIcon,
	pp: PascalIcon,
	p: PascalIcon,
	lpr: LazarusprojectIcon,
	lps: LazarusprojectIcon,
	lpi: LazarusprojectIcon,
	lfm: LazarusprojectIcon,
	lrs: LazarusprojectIcon,
	lpk: LazarusprojectIcon,
	dpr: DelphiprojectIcon,
	dproj: DelphiprojectIcon,
	dfm: DelphiprojectIcon,
	sass: ScssIcon,
	sc: ScalaIcon,
	scala: ScalaIcon,
	scpt: BinaryIcon,
	scptd: BinaryIcon,
	scss: ScssIcon,
	sentinel: SentinelIcon,
	sig: FileIcon,
	sketch: FileIcon,
	slddc: FileIcon,
	sldm: FileIcon,
	sldx: FileIcon,
	sln: SlnIcon,
	sls: FileIcon,
	slx: FileIcon,
	smv: FileIcon,
	so: BinaryIcon,
	sol: SolIcon,
	sql: SqlIcon,
	sqlite: SqliteIcon,
	sqlite3: SqliteIcon,
	src: CertIcon,
	sss: FileIcon,
	sst: CertIcon,
	stl: CertIcon,
	storyboard: StorybookIcon,
	styl: StylusIcon,
	suo: SuoIcon,
	svelte: SvelteIcon,
	svg: SvgIcon,
	swc: FileIcon,
	swf: FileIcon,
	swift: SwiftIcon,
	tar: ZipIcon,
	tcl: FileIcon,
	templ: TmplIcon,
	tesc: OpenglIcon,
	tese: OpenglIcon,
	tex: LatexIcon,
	texi: LatexIcon,
	tf: TerraformIcon,
	tfstate: TerraformIcon,
	tfvars: TerraformvarsIcon,
	tgz: ZipIcon,
	tikz: LatexIcon,
	tlg: LogIcon,
	tmlanguage: XmlIcon,
	tmpl: TmplIcon,
	todo: TodoIcon,
	toml: TomlIcon,
	tpl: SmartyIcon,
	tres: TresIcon,
	tscn: TscnIcon,
	tst: FileIcon,
	tsx: ReacttsIcon,
	jsx: ReactjsIcon,
	tt2: FileIcon,
	ttf: FileIcon,
	twig: TwigIcon,
	txt: TxtIcon,
	ui: UiIcon,
	unity: ShaderlabIcon,
	user: UserIcon,
	v: VIcon,
	vala: FileIcon,
	vapi: FileIcon,
	vash: FileIcon,
	vbhtml: HtmlIcon,
	vbproj: CsprojIcon,
	vcxproj: CsprojIcon,
	vert: OpenglIcon,
	vhd: VhdIcon,
	vhdl: VhdlIcon,
	vsix: VscodeIcon,
	vsixmanifest: ManifestIcon,
	wasm: WasmIcon,
	wav: AudiowavIcon,
	webp: ImagewebpIcon,
	wgsl: WgslIcon,
	wll: FileIcon,
	woff: FileIcon,
	eot: FileIcon,
	woff2: FileIcon,
	wv: AudiowvIcon,
	wxml: XmlIcon,
	wxss: CssIcon,
	xcodeproj: FileIcon,
	xfl: XmlIcon,
	xib: FileIcon,
	xlf: XmlIcon,
	xliff: XmlIcon,
	xls: FileIcon,
	xlsm: FileIcon,
	xlsx: FileIcon,
	xsf: FileIcon,
	xsn: FileIcon,
	xtp2: FileIcon,
	xvc: FileIcon,
	xz: ZipIcon,
	yy: FileIcon,
	yyp: FileIcon,
	zig: ZigIcon,
	zip: ZipIcon,
	zipx: ZipIcon,
	zz: ZipIcon,
	deflate: ZipIcon,
	brotli: BrotliIcon,
	kra: KritaIcon,
	mgcb: MgcbIcon,
	anim: AnimIcon,
	'cy.ts': CypresstsIcon,
	'cy.js': CypressjsIcon,
	hx: HaxeIcon,
	hxml: HaxemlIcon,
	gr: GrainIcon,
	slim: SlimIcon,
	obj: ObjIcon,
	mtl: MtlIcon,
	bicepparam: BicepparamIcon,
	proto: ProtoIcon,
	wren: WrenIcon,
	'docker-compose.yml': DockerIcon,
	excalidraw: ExcalidrawIcon,
	'excalidraw.json': ExcalidrawIcon,
	'excalidraw.svg': ExcalidrawIcon,
	'excalidraw.png': ExcalidrawIcon,
	bazel: BazelIcon,
	bzl: BazelIcon,
	bazelignore: BazelignoreIcon,
	bazelrc: BazelIcon,
	http: HttpIcon,
	rkt: RacketIcon,
	rktl: RacketIcon,
	bru: BrunoIcon,
	nelua: NeluaIcon,
	mermaid: MermaidIcon,
	mmd: MermaidIcon,
	bal: BallerinaIcon,
	hash: HashIcon,
	gleam: GleamIcon,
	lock: LockIcon,
	yang: YangIcon,
	yin: YinIcon,
	mdc: CursorIcon,
	uml: PlantumlIcon,
	Identifier: IdentifierIcon,
	cls: SalesforceIcon,
	'.instructions.md': InstructionsIcon,
	'.instructions.txt': InstructionsIcon,
	'.instructions.json': InstructionsIcon,
	'.instructions.yaml': InstructionsIcon,
	'.instructions.yml': InstructionsIcon,
	silq: SilqIcon,
	eraserdiagram: EraserIcon,
};
